use_frameworks!

target 'ReactiveAFNetworking_Example' do
  pod 'ReactiveObjC', '1.0.2'
  pod 'AFNetworking', '4'

  pod 'ReactiveAFNetworking', :path => '../'

  target 'ReactiveAFNetworking_Tests' do
    inherit! :search_paths

    
  end
end
